### ISSUE TITLE
"Couldn't find import path from atRule" with `file-extension` rule

### ISSUE THREAD

**Issue by keganlance** [electrovir/stylelint-plugin-import#20]
When trying to use the the `file-extension` rule like this:
```json
    "plugin-import/file-extension": {
      "mode": "require"
    },
```

And having some css like this:
```css
@import url("some-path.css");
```

It gives the following errors:
```
    Couldn't find import path from atRule

      at <input css xm2qcJ>:1:1
      at extractImportPath (node_modules/.pnpm/stylelint-plugin-import@1.0.12/node_modules/stylelint-plugin-import/dist/import-path.js:13:15)
      at node_modules/.pnpm/stylelint-plugin-import@1.0.12/node_modules/stylelint-plugin-import/dist/rules/file-extension/file-extension.rule.js:30:94
      at node_modules/.pnpm/postcss@8.4.18/node_modules/postcss/lib/container.js:132:16
      at node_modules/.pnpm/postcss@8.4.18/node_modules/postcss/lib/container.js:55:18
      at Root.each (node_modules/.pnpm/postcss@8.4.18/node_modules/postcss/lib/container.js:41:16)
      at Root.walk (node_modules/.pnpm/postcss@8.4.18/node_modules/postcss/lib/container.js:52:17)
      at Root.walkAtRules (node_modules/.pnpm/postcss@8.4.18/node_modules/postcss/lib/container.js:130:17)
      at Object.ruleCallback (node_modules/.pnpm/stylelint-plugin-import@1.0.12/node_modules/stylelint-plugin-import/dist/rules/file-extension/file-extension.rule.js:25:14)
      at Object.ruleCallback (node_modules/.pnpm/stylelint-rule-creator@5.1.0/node_modules/stylelint-rule-creator/dist/default-rule.js:205:38)
      at node_modules/.pnpm/stylelint-rule-creator@5.1.0/node_modules/stylelint-rule-creator/dist/rule.js:14:32
      at node_modules/.pnpm/stylelint@14.14.1/node_modules/stylelint/lib/lintPostcssResult.js:114:8
          at Array.map (<anonymous>)
      at lintPostcssResult (node_modules/.pnpm/stylelint@14.14.1/node_modules/stylelint/lib/lintPostcssResult.js:105:18)
      at lintSource (node_modules/.pnpm/stylelint@14.14.1/node_modules/stylelint/lib/lintSource.js:111:8)
      at Function.standalone [as lint] (node_modules/.pnpm/stylelint@14.14.1/node_modules/stylelint/lib/standalone.js:129:26)
```

**Comment by electrovir** [comment]
Fix has been released on npm within [version 1.0.13](https://www.npmjs.com/package/stylelint-plugin-import/v/1.0.13). Please try that new version and re-open this ticket if it does not work for you!
